FROM ubuntu:20.04
# 作者信息
MAINTAINER maxiaoming "mxm41121@163.com"

# 修改更新源为阿里云
ADD sources.list /etc/apt/sources.list

# 前端
ADD CHARGE_SERVICE_VUE/ /home/project/xiangyun/CHARGE_SERVICE_VUE/
# 后端
ADD recharge_platform/ /home/project/xiangyun/recharge_platform/
# 队列服务
ADD CHARGE_SERVICE_KEEPER/ /home/project/xiangyun/CHARGE_SERVICE_KEEPER/
# python包管理requirements
COPY requirements.txt /home/project
# supervisord配置文件supervisord.conf
COPY supervisord.conf /home/project

# 设置系统时区
ENV TZ Asia/Shanghai

# 设置语言
ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8

# 安装基础环境
# 层数最多127层  可使用 && 拼接
RUN apt-get clean && apt-get update --fix-missing && apt-get upgrade -y
RUN apt-get install -y tzdata locales cron vim wget dos2unix zlib1g-dev build-essential nginx supervisor libmysqlclient-dev libpcre3 libpcre3-dev gcc
RUN apt install -y libffi-dev libssl-dev
RUN mkdir -p /usr/local/python3.8 /mnt/logs/xiangyun
RUN cd /usr/local
RUN wget https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tar.xz && tar -xvf Python-3.8.5.tar.xz
RUN cd Python-3.8.5 && ./configure --prefix=/usr/local/python3.8 && make && make install
RUN ln -sf /usr/local/python3.8/bin/python3.8 /usr/local/bin/python3.8
RUN wget https://bootstrap.pypa.io/get-pip.py && python3.8 get-pip.py
RUN ln -sf /usr/local/python3.8/bin/pip3.8 /usr/local/bin/pip3.8
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && ln -s /mnt/logs /home/project/xiangyun/logs
RUN pip3.8 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r /home/project/requirements.txt
RUN ln -sf  /usr/local/python3.8/bin/uwsgi /usr/local/bin/uwsgi3.8

# 设置映射端口（映射多个端口时，继续添加EXPOSE即可）
EXPOSE 10005 10006 10007 10008

# 设置映射目录
VOLUME /mnt/logs

# supervisord启动
# COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
# CMD ["/usr/bin/supervisord"]
